const dietLabels = [
  'Balanced',
  'High-fiber',
  'High-protein',
  'Low-carb',
  'Low-fat',
  'Low-sodium',
];

const healthLabels = [
  'alcohol-cocktail',
  'alcohol-free',
  'celery-free',
  'crustacean-free',
  'dairy-free',
  'DASH',
  'egg-free',
  'fodmap-free',
  'fish-free',
  'gluten-free',
  'immuno-supportive',
  'keto-friendly',
  'kidney-friendly',
  'kosher',
  'low-fat-abs',
  'low-potassium',
  'low-sugar',
  'lupine-free',
  'Mediterranean',
  'mollusk-free',
  'mustard-free',
  'no-oil-added',
  'paleo',
  'peanut-free',
  'pescatarian',
  'pork-free',
  'red-meat-free',
  'sesame-free',
  'shellfish-free',
  'soy-free',
  'sugar-conscious',
  'sulfite-free',
  'tree-nut-free',
  'vegan',
  'vegetarian',
  'wheat-free',
];

const cuisineTypeLabels = [
  'American',
  'Asian',
  'British',
  'Caribbean',
  'Central Europe',
  'Chinese',
  'Eastern Europe',
  'French',
  'Indian',
  'Italian',
  'Japanese',
  'Kosher',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'Nordic',
  'South American',
  'South East Asian',
];

const dishTypeLabels = [
  'Biscuits and cookies',
  'Bread',
  'Cereals',
  'Condiments and sauces',
  'Desserts',
  'Drinks',
  'Main course',
  'Pancake',
  'Preps',
  'Preserve',
  'Salad',
  'Sandwiches',
  'Side dish',
  'Soup',
  'Starter',
  'Sweets',
];

const mealTypeLabels = ['Breakfast', 'Dinner', 'Lunch', 'Snack', 'Teatime'];

export {
  dietLabels,
  healthLabels,
  cuisineTypeLabels,
  dishTypeLabels,
  mealTypeLabels,
};
